#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 10 16:32:32 2021

@author: supphakit
"""

import os
import numpy as np
import healpy as hp
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
from astropy.io import fits
from astropy.table import Table
from astropy.coordinates import SkyCoord
import astropy.units as u
import scipy.interpolate

plt.style.use('dark_background')
plt.rcParams.update({"figure.facecolor" : '#0f0f0f00'})

#Add
data = fits.open('/home/supphakit/Desktop/Research/gll_psc_v22.fit')
#T = Table(data[1].data).show_in_browser()
t = Table(data[1].data)

#plot
plt.figure(figsize=(20,10))
plt.scatter((t['GLON']+180)%360 -180, t['GLAT'], marker ='.', s= 5 )
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.legend(loc='upper left')
plt.show()

#molling
plt.figure(figsize=(20,10))
ax = plt.subplot(projection='mollweide')
gal = SkyCoord(t['GLON'][:],t['GLAT'][:], frame='galactic',unit=u.deg)
ax.scatter(gal.l.wrap_at('180d').radian, gal.b.radian, s=5)
ax.grid(alpha=0.7)





#Select
new_glon = np.logical_and(t['GLON'] >=52, t['GLON']<=55)
new_tg = t[new_glon]
new_glat = np.logical_and(new_tg['GLAT'] >= -1.2, new_tg['GLAT'] <=1.8)
new_t = new_tg[new_glat]

#new_t = new_tg[new_glat].show_in_browser()
#add label

fix ,ax = plt.subplots(figsize=(20,10))
ax.scatter((new_t['GLON'] +180)%360 - 180, new_t['GLAT'],facecolor='none', edgecolor = 'y' , s=80)
for i, txt in enumerate(new_t['Source_Name']):           
    ax.annotate(txt, (new_t['GLON'][i]-0.1, new_t['GLAT'][i]+0.05))
ax.set_xlabel("Galactic Longitude (deg)")
ax.set_ylabel("Galactic Latitude (deg)")
ax.set_xlim(53.5-1.5, 53.5+1.5)
ax.set_ylim(0.3-1.5, 0.3+1.5)
ax.grid(alpha=0.5)

#open map
mapp = fits.open('/home/supphakit/Desktop/Research/Photon database/L210510051548F357373F73_PH00.fits')
t_mapp = Table(mapp[1].data)
#t_mapp.show_in_browser()

#photon local map
fig, ax = plt.subplots(figsize=(20,10))

NBINS = (274)

ax.hist2d(t_mapp['L'], t_mapp['B'], NBINS , cmap = plt.cm.jet , norm= LogNorm(),)

ax.scatter((new_t['GLON'] +180)%360 - 180, new_t['GLAT'],facecolor='none', edgecolor = 'y' , s=80)

for i, txt in enumerate(new_t['Source_Name']):           
    ax.annotate(txt, (new_t['GLON'][i]-0.1, new_t['GLAT'][i]+0.05))
   

ax.set_xlabel("Galactic Longitude (deg)")
ax.set_ylabel("Galactic Latitude (deg)")
ax.set_xlim(53.5-1.5, 53.5+1.5)
ax.set_ylim(0.3-1.5, 0.3+1.5)
ax.grid(alpha=0.5)


#combined
fig, ax = plt.subplots(figsize=(20,10))
x = t_mapp['L']
y = t_mapp['B']
z = t_mapp['ENERGY']
xi,yi = np.linspace(x.min(), x.max(),1000),np.linspace(y.min(), y.max(),100)
xi,yi = np.meshgrid(xi,yi)
rbf = scipy.interpolate.Rbf(x,y,z,function='linear')
zi = rbf(xi,yi)
plt.contourf(xi,yi,zi, cmap='inferno')
ax.scatter((new_t['GLON'] +180)%360 - 180, new_t['GLAT'],facecolor='none', edgecolor = 'y' , s=80)
for i, txt in enumerate(new_t['Source_Name']):           
    ax.annotate(txt, (new_t['GLON'][i]-0.1, new_t['GLAT'][i]+0.05))
#add location
NBINS = (274)


ax.scatter(t_mapp['L'], t_mapp['B'], cmap = 'gist_yarg', norm= LogNorm())

ax.scatter((new_t['GLON'] +180)%360 - 180, new_t['GLAT'],facecolor='none', edgecolor = 'y' , s=80)
##   
cbar = plt.colorbar()
ax.set_xlabel("Galactic Longitude (deg)")
ax.set_ylabel("Galactic Latitude (deg)")
ax.set_xlim(53.5-1.5, 53.5+1.5)
ax.set_ylim(0.3-1.5, 0.3+1.5)
ax.grid(alpha=0.5)

cbar.set_label("Energy ( MeV )")    
plt.show()

#by Contourf
fig, ax = plt.subplots(figsize=(20,10))
x = t_mapp['L']
y = t_mapp['B']
z = t_mapp['ENERGY']
contour = plt.contour(xi,yi,zi ,cmap='inferno')
ax.scatter((new_t['GLON'] +180)%360 - 180, new_t['GLAT'],facecolor='none', edgecolor = 'y' , s=80)
for i, txt in enumerate(new_t['Source_Name']):           
    ax.annotate(txt, (new_t['GLON'][i]-0.1, new_t['GLAT'][i]+0.05))
ax.clabel(contour, fontsize=10)   
cbar = plt.colorbar()
ax.set_xlabel("Galactic Longitude (deg)")
ax.set_ylabel("Galactic Latitude (deg)")
ax.set_xlim(53.5-1.5, 53.5+1.5)
ax.set_ylim(0.3-1.5, 0.3+1.5)
ax.grid(alpha=0.5)

#by
fig, ax = plt.subplots()
ax.scatter(x, y, c=z, s=50)
cbar = plt.colorbar()
ax.set_xlabel("Galactic Longitude (deg)")
ax.set_ylabel("Galactic Latitude (deg)")
ax.set_xlim(53.5-1.5, 53.5+1.5)
ax.set_ylim(0.3-1.5, 0.3+1.5)
ax.grid(alpha=0.5)
plt.show()


